import LogoSearch from "./LogoSearch"
import Navbar from "./Navbar"
import MusicPlay from "./MusicPlay"
import Head from "next/head";

function Layout({children}) {

    return (
    
    <div className='flex flex-col w-full '>
        <Head>
            <title>Musica</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
        </Head>
        <LogoSearch/>
        <div className="flex md:mx-6 w-full">
            <Navbar/>
            <div className="m-12 flex w-full">{children}</div>
        </div>
        <div className="flex w-full z-20">
            <MusicPlay/>
        </div>
        
        
    </div>
)
}




export default Layout