import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import TopChart from '../components/TopChart'
import NewRelease from '../components/NewRelease'
import PopularArea from '../components/PopularArea'

const Home: NextPage = () => {
  return (
    <div className="w-full">
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
      </Head>

      <main className="flex m-5 flex-col text-white w-10/12">
        
        <div className='flex flex-col md:flex-row w-full justify-between'>
          <Header  />
          <TopChart />
        </div>
        <NewRelease/>
        <PopularArea/>
      </main>
    </div>
  )
}

export default Home
