import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import TopChart from '../components/TopChart'
import NewRelease from '../components/NewRelease'
import PopularArea from '../components/PopularArea'
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import { storeWrapper } from '../store/index';
import { fetchMusic } from '../store/fetchMusicSlice'
import { useDispatch,useSelector } from 'react-redux'
import { EnhancedStore } from '@reduxjs/toolkit'

const Home: NextPage = () => {
  
  
  return (
    <div className="w-full">
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
      </Head>

      <main className="flex m-5 flex-col text-white w-10/12">
        
        <div className='flex flex-col md:flex-row w-full justify-between'>
          <Header  />
          <TopChart />
        </div>
        <NewRelease/>
        <PopularArea/>
      </main>
    </div>
  )
}



export const getStaticProps: GetStaticProps = storeWrapper.getStaticProps((store)  => async () => {
  const data = await fetch('https://musica-api.up.railway.app/new');
  console.log("this function ran")
  const posts = await data.json();
  store.dispatch(fetchMusic(posts));
  
});


export default Home
